feat:ログイン、アカウント作成フォームを作りました。
mikan19/PHP-ToDo pull request #9
Opened 2023-06-12 14:34 UTC by mikan19

## 作業対象

[作業をした教材のURL]
[https://www.notion.so/14-ToDo-6819dc7b90be49d58bcbc4541ea464c2?pvs=4](url)
[作成したページのURL(user/signup.php)
(http://localhost:8080/user/signup.php)

## 作業詳細

todoアプリのアカウント作成フォーム、ログインフォーム、ヘッダーを作成しました。

https://github.com/mikan19/PHP-ToDo/assets/128659635/f916ed62-62e3-4206-ae08-86815eb54f86

2023-06-12 22:14 UTC, KatsuyaTanaka95 requested changes
レビューさせていただきました！
ご修正をお願いします！😊

2023-06-12 22:14 UTC, KatsuyaTanaka95 commented on src/public/style.css
> +}
機能作成とは関係ないのですが、レビューさせていただきます！！
要素タグにスタイルを指定しない方が良いかと思います！😭
**class属性にスタイルを指定する**ようにするとよいです！😊

要素タグとは、「aタグ」「headerタグ」等のことです！
これらにスタイルを指定すると、別の「aタグ」には、他のスタイルを指定したいとなったときに、修正が必要になります。

class属性とは、navタグ内にある「class="nav-top"」のことです！
navタグに指定せず、「class="nav-top"」にスタイルを指定するとよいです！
例を別で書いておきます！

2023-06-12 22:14 UTC, KatsuyaTanaka95 commented on src/public/style.css
> +}
例：以下のように変更すると良いです！😊
. nav-top {
 margin: 0 0 0 auto;
}

2023-06-12 22:14 UTC, KatsuyaTanaka95 commented on src/public/user/signin_complete.php
> +        exit;
ガード節でかけるとよいですね！！
if文の中にif文は書かないようにできるとよいです！😭
elseも書かないようにすると良いです！😭

以下のような条件にするとガード節になります！
```
if (!empty($email) || !empty($password)) {
 
}

```

2023-06-13 14:38 UTC, mikan19 commented on src/public/user/signin_complete.php
> +        exit;
if (!empty($email) || !empty($password)) {
 
}
これはどちらか一方が空じゃない(入力がある)場合条件内の処理が実行される、ということになると思うのですが、このコードを使ってどのようにガード節にしたら良いでしょうか？
色々と考えてみましたが行き詰まってしまいました😭 ご教授いただきたいです🙇‍♀️

2023-06-14 04:33 UTC, merged